"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"files": [
  {
    "source": "/l10n/bundle.l10n.json",
    "translation": "/l10n/bundle.l10n.%two_letters_code%.json"
  },
  {
    "source": "/package.nls.json",
    "translation": "/package.nls.%two_letters_code%.json"
  }
]
