"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "l10n/bundle.l10n.json",
    "translation": "l10n/bundle.l10n.%locale%.json"
  }
]
