
name: Translations CI
permissions:
  contents: read
  models: read

on:
  push:
    branches: ["main"]
    paths:
      - "l10n/**"
      - ".github/workflows/lang-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "l10n/**"
      - ".github/workflows/lang-ci.yml"

jobs:
  validate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        id: installpython
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install LLM with GitHub Models
        run: python -m pip install llm-github-models
      - name: Review l10n changes
        run: | 
          git --no-pager diff -p --no-color origin/main...${{ github.sha }} l10n | llm prompt -m github/gpt-5-mini \
          "For each of the changed lines in this output from git diff (those starting +), comment on whether the translation for that
          language is blatantly inaccurate or offensive. \
          Use the formatting for GitHub Actions, e.g. \
              ::warning file=app.py,line=10,col=5::Code formatting issues detected"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
